name: Update website

on:
  release:
    types:
      - published
      - deleted
      - edited

jobs:
  update_website:
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Update website on release
        uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1.3.1
        with:
          workflow: Deploy
          repo: anikku-app/anikku-app.github.io
          ref: "refs/heads/master"
          token: "${{ secrets.BOT_PAT }}"
